### ISSUE TITLE
Question regarding registration

### ISSUE THREAD

**Issue by dataMaster-Kris** [labsyspharm/ashlar#103]
https://github.com/labsyspharm/ashlar/blob/2587ea683c924e1b6d3cc4913e17532266471c5d/ashlar/utils.py#L34-L46

Hello, I have a question regarding the above code chunk.

I got erroneous results from ASHLAR's registration in my initial tests. ASHLAR did not report any errors but the output images were translated by large distances, much greater than the true offsets. This didn't happen with all the images but only some. Hence, I looked into the python scripts. The above code chunk is testing four possible offsets to account for cases with "shift in the wrong quadrant" as described in the comment. The tested shifts include large offsets. That seems to be the source of issue. Can you please check? For example, if `shift = [2, 3]`, and `img1.shape = [1080, 1080]`, running the lines 37-40 above gives:
```
>>> shifts
[(2, 3), (2, -1077), (-1078, 3), (-1078, -1077)]
``` 

Is this expected?

**Comment by jmuhlich** [comment]
Those large offsets are expected to be present in the `shifts` list, but the cross-correlation computed for those large offsets should be almost zero so they should never "win" in the `argmax` call on line 45. Can you explain a bit more about your dataset and how you're running Ashlar? It would be helpful to see your data if it's possible to share. You can reach out to me via the email address in my profile if you want to coordinate that privately.

**Comment by dataMaster-Kris** [comment]
Hi @jmuhlich,

Thanks for looking into it. I am not sure if I fully understand the logic explained in the comment lines https://github.com/labsyspharm/ashlar/blob/2587ea683c924e1b6d3cc4913e17532266471c5d/ashlar/utils.py#L34-L36

If `shift = [2, 3]`, shouldn't the four tested values per the above comment be `[(2,3), (2,-3), (-2,3), (-2,-3)]`?

I ran into the issue a while ago, when I was first trying to register images after correcting raw (1080,1080) TIFF files for illumination variation with BaSiC. They weren't great quality images, which might be one of the reasons. If I have the issue again with any of the images, I'll share a reproducible example.

**Comment by dataMaster-Kris** [comment]
@jmuhlich Thanks a lot for your time and the detailed explanation! I understand the logic better now. One thing I didn't get is, what is the issue with running BaSiC before registration? I understand that it may not be needed because of the LoG filtering by ASHLAR, but why should it be a problem?

**Comment by jmuhlich** [comment]
Sorry, performing your own illumination correction isn't bad at all. Just unnecessary. :) If it works better in your workflow to do it that way though, go ahead. The Ashlar results will be the same.

**Comment by dataMaster-Kris** [comment]
Thanks for the clarification!
