### ISSUE TITLE
Alternatives to linear blending

### ISSUE THREAD

**Issue by amjams** [labsyspharm/ashlar#110]
Hello,

Is there a way to use alternatives to linear blending when tiles overlap or is this not supported yet?

From the paper:

"Where neighboring image tiles overlap in the mosaic, they are combined with linear blending or one of **several other user-selectable blending functions.**"

**Comment by amjams** [comment]
I'm looking for a "no-blending" option, where you essentially give one tile priority over the other if they overlap. So maybe if I can access the blending function in the code, this is just equivalent to setting some alpha value to 1?

**Comment by jmuhlich** [comment]
Sure, edit `ashlar/reg.py`. In `Mosaic.run`, change `func = utils.pastefunc_blend if not debug else np.add` to just `func = None`. Here is the line in the latest version of the code -- the line number may vary depending on what version you're using:

https://github.com/labsyspharm/ashlar/blob/master/ashlar/reg.py#L1095

**Comment by amjams** [comment]
Thanks, it works.
