### ISSUE TITLE
Output tile positions

### ISSUE THREAD

**Issue by sophiamaedler** [labsyspharm/ashlar#117]
I sadly wasn't able to find anything in the documentation, but hopefully you can quickly lead me in the correct direction.
I am using ashlar to stitch and align larger imaging datasets (3 channel imaging, ~2000 image tiles per project) using a python workflow. I then use the stitched images in a segmentation/classification pipeline. For my downstream analysis it would be useful to know which part of the stitched image came from which image tile so that I for example can eliminate cells that came from an out-of-focus tile. Is there some possibility to output this information while stitching?

**Comment by jmuhlich** [comment]
Are you using the ashlar python API in your own python code, or are you using the ashlar command line script? The command line script does not currently write tile positions but if you are using it via the python API it will only require a few lines of code to write tile positions. `aligner.positions` is a numpy array of shape `(num_tiles, 2)` containing the `Y, X` coordinates of each tile, so you can write that out as a CSV file or whatever format you like. Just remember the first column is the *Y* coordinate!

**Comment by sophiamaedler** [comment]
Hi @jmuhlich,
I use Ashlar within my own python code. That was exactly what I was looking for! Thanks so much for your help :) 
Cheers
Sophia
