### ISSUE TITLE
No way to switch from combing to continuous merge when using the 'fileseries' option

### ISSUE THREAD

**Issue by MNM-TB** [labsyspharm/ashlar#126]
Thank you for a great tool! I'm trying to migrate part of our analysis pipeline from MIST in ImageJ to Ashlar. Most things look positive but I have got stuck on a stopper. The image series we generate uses a "back and forth" paradigm so the first row is imaged left-to-right and the second row right-to-left. In MIST this is called "continuous" instead of "combing". 

When I manually specify the "fileseries" and the correct width and height it merges but always uses the combing approach, resulting in an erroneous merge.

Is this possible to solve? Thanks'

**Comment by jmuhlich** [comment]
Yes, you can add `layout=snake` to the fileseries options.
