### ISSUE TITLE
5 channel images error

### ISSUE THREAD

**Issue by ciszew** [labsyspharm/ashlar#135]
I have been testing ashlar to process (stich and register) multiple rounds of images from codex. After some trail and error i got to the point when i get satisfactory output (there  seems to be some stitching artefacts in overlap area but i will tweak SHIFT and SIGMA values to work on that).
The problem i got stack on is an error below which i seems to get only when using 5 channel images. I created test set with 3 channels only which seems to work fine but when using generated side by side 5 channels set of images im getting below error.
For acquisition i use Dragonfly 200 confocal, i convert ims files (direct output from dragonfly, looks like ashlar doesnt have ims compactible reader) to ome.tif files using bfconvert command line tool, ashlar version 1.16.0

~/.local/lib/python3.8/site-packages/ashlar$ ashlar 'fileseries|/nfs/././test3|pattern=05242022_ashlar_test3_F{series}.ims.ome.tiff|width=6|height=20|pixel_size=0.1507|overlap=0.1|layout=snake|direction=vertical'  --flip-y --flip-mosaic-y --pyramid --maximum-shift 30  -o /mnt/d/././.ome.tif
Stitching and registering input images
Cycle 0:
    reading fileseries|/nfs/././test3|pattern=05242022_ashlar_test3_F{series}.ims.ome.tiff|width=6|height=20|pixel_size=0.1507|overlap=0.1|layout=snake|direction=vertical
WARNING: Some neighboring tiles have zero overlap.
Traceback (most recent call last):
  File "/home/hdid/.local/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/home/hdid/.local/lib/python3.8/site-packages/ashlar/scripts/ashlar.py", line 212, in main
    return process_single(
  File "/home/hdid/.local/lib/python3.8/site-packages/ashlar/scripts/ashlar.py", line 243, in process_single
    edge_aligner.run()
  File "/home/hdid/.local/lib/python3.8/site-packages/ashlar/reg.py", line 485, in run
    self.compute_threshold()
  File "/home/hdid/.local/lib/python3.8/site-packages/ashlar/reg.py", line 550, in compute_threshold
    o1, o2 = random_state.randint(max_offset, size=2)
  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: high <= 0

**Comment by jmuhlich** [comment]
Thanks for reporting this, it's definitely a bug in Ashlar. `skimage.io.imread`, which we used to read `fileseries` images, returns 3- and 4-channel images in Y,X,C order for matplotlib compatibility but returns all other 3-D images as C,Y,X. We will update Ashlar to correct for this.

**Comment by jmuhlich** [comment]
I just fixed this issue. You can `pip install` directly from github to obtain this fix right away -- I'm going to wait until I finish a few other things to release a new official version.
