### ISSUE TITLE
Stitching output in grey colour.

### ISSUE THREAD

**Issue by kuldeep203** [labsyspharm/ashlar#164]
i want output in same colour as it was in input.
i have tried the cmd as shown:
ashlar "fileseries|/home/kuldeep/Downloads/Inferencing_with_Button/Image_Data/room|pattern=room{series:1}.jpg|overlap=0.2|width=10|height=1" --output-channels 0
but it is giving output in grey colour but i want it as the images was in the input.

**Comment by jmuhlich** [comment]
Sorry, the output from RGB input is not proper RGB tiff yet but this is on our list of things to do. The R, G, and B channels are actually all there but they are in separate grayscale channels in the tiff. You should be able to write a bit of code to combine them or use a tool like Fiji to do it.

**Comment by kuldeep203** [comment]
i solve the issue by combining all the three channels.
