### ISSUE TITLE
Support of non-regular acquisition grids

### ISSUE THREAD

**Issue by joshua-gould** [labsyspharm/ashlar#195]
It would be great to "Support of non-regular acquisition grids, which includes ‘intelligent acquisitions’ where some of the image blocks can be missing if only background is present" like BigStitcher. Thanks

**Comment by jmuhlich** [comment]
What kind of microscope / file format do you have? Many Bioformats-supported formats generally already allow this without requiring a dedicated mapping file.

If you have the X,Y grid coordinates encoded in your image filenames, you can use Ashlar's `filepattern` reader (it's undocumented but I can provide help with it here if relevant). Even if your filenames don't encode X,Y then you could still create a directory of symbolic links to the original files where the link names do encode the X,Y position.

If your images are TIFF files, it's possible to create a "companion OME-XML" file that provides the mapping. This is the most complicated option but the most flexible.

We're working on a way to provide a more friendly mapping file format but it's still in the planning stages.

**Comment by joshua-gould** [comment]
Thanks for your reply. My input images are in nd2 format (one image per
tile) and include the stage position in the file metadata. Perhaps I'm not
understanding how to input these images to ashlar?

**Comment by joshua-gould** [comment]
@jmuhlich Can you please give an example of how to input a directory of nd2 files that contain the stage position to ashlar? Thanks.
