### ISSUE TITLE
Issues stitching imaged tissue sections

### ISSUE THREAD

**Issue by sophiamaedler** [labsyspharm/ashlar#205]
Thanks for the great package! Usually we get really nice stitching results but currently we are struggling with a group of datasets and are not sure what the problem is and are hoping for some insights. 

Briefly to our pipeline: We image our tissue sections on an Opera Phenix Microscope in 40X magnification with 10% overlap. We then export individual image tiles and name them with a row and column identifier. We then call up the ashlar stitching API in a python script (see attached file).

Unfortunately the stitching results look strange, with most tiles not being corrected as can be clearly seen in the attached quality control plots. 

[QC_edge_quality.pdf](https://github.com/labsyspharm/ashlar/files/13489872/QC_edge_quality.pdf)
[QC_edge_scatter.pdf](https://github.com/labsyspharm/ashlar/files/13489873/QC_edge_scatter.pdf)

This leads to stitching artefacts in some parts of the image. Usually we would expect some of the tiles in the edges to show a high error since these tiles do not contain any tissue but the tiles in the center should align with one another which we aren't seeing with these datasets. 

If I manually check some of the image tiles according to their positioning and look at them beside each other, we can see that we definitely have 10% overlap and (in my opinion) ashlar should be able to find a good alignment between the tiles. 
![screenshot_2023-11-20_at_18 02 09_720](https://github.com/labsyspharm/ashlar/assets/15019107/620608dc-bd02-4f3f-b867-72d0e13f44dd)

I have also tried to do a little bit of debugging and looked at the results from the aligner.debug function on edges between graph neighbours. 

For some of the early tiles we get output like this: 

<img width="639" alt="Screenshot 2023-11-28 at 16 21 00" src="https://github.com/labsyspharm/ashlar/assets/15019107/30799d9d-98ad-43af-8914-2c9d1c12be98">
 
So probably these are some of the tiles that are empty as to be expected. 

But for most of the edges we get output like this:

<img width="649" alt="Screenshot 2023-11-28 at 16 21 47" src="https://github.com/labsyspharm/ashlar/assets/15019107/d4d3651e-35e7-4e4c-9b7a-1252644f716f">

I am not 100% sure what each plot is showing, but at first glance it looks like it correctly trying to align two matching edges with one another? 

If you give me an email address I would be happy to forward this dataset to you. 

Here the code I use to run the stitching:
[stitching_code.txt](https://github.com/labsyspharm/ashlar/files/13490042/stitching_code.txt)

**Comment by Yu-AnChen** [comment]
Hi @sophiamaedler could you share a screenshot of the thumbnail and also what the edge scatter plot looks like if you set `filter_sigma=1` in the `EdgeAligner`? Also if you this info - what's the pixel size in the image (µm/pixel)?

**Comment by sophiamaedler** [comment]
@Yu-AnChen thanks for the quick response. 

If I set filter_sigma=1 then the edge scatter plot looks like this: 
<img width="473" alt="Screenshot 2023-11-29 at 00 06 54" src="https://github.com/labsyspharm/ashlar/assets/15019107/b46cc04a-beec-4439-bf10-200803f26796">
<img width="1073" alt="Screenshot 2023-11-29 at 00 07 09" src="https://github.com/labsyspharm/ashlar/assets/15019107/43adae56-9e44-45c0-a400-5c7cec76f218">

This definitely looks much better already. I will check out the data in detail as soon as I can fully load the image with a faster data connection and check for any further stitching artefacts, but this could already be the fix I was hoping for. Could you briefly explain what the sigma parameter does and how you should select an appropriate parameter?

Just to ensure completeness in my response here the other information you asked for: 
- The pixel size should be 0.149494µm/pixel

- Here is an overview image from the microscope we acquired it on:
<img width="968" alt="Screenshot 2023-11-28 at 23 57 28" src="https://github.com/labsyspharm/ashlar/assets/15019107/887eaab2-c1f8-4b68-ab44-65ebc52d78c0">

 - And here the thumbnail generated in Ashlar:
<img width="883" alt="Screenshot 2023-11-29 at 00 00 03" src="https://github.com/labsyspharm/ashlar/assets/15019107/b2141cdd-918a-4708-8dfd-b55490203ba8">

Both look fairly good. The stitching itself is also not completely wrong but the tiles are not as well aligned as we are used to with Ashlar and we see some smaller stitching artefacts. I will check if we still see the same with the new sigma parameter and get back to you.
