### ISSUE TITLE
Fileseries with large overlap

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/ashlar#213]
Dear ashlar devs,

I am trying to stitch some .nd2 files that have been provided by collaborators. 
They performed CyCIF in a spinning confocal setup at 40X.
Possible issue: Z-alignment was performed manually by visual inspection of nuclei.
 
Each file is a single tile from a cycle, containing four channels.
I have 81 files per cycle, and in the example dataset I am linking to there are two cycles (I can provide more if needed)

Link:
https://nextcloud.mdc-berlin.de/index.php/s/3ycTHmLdbH7GA4w
Password(enforced): 
JD25(cF8?W

In there you will find the raw images, and the files I used to obtain the plots, the jupyter notebooks should be sufficient I hope. 

Initially I ran ashlar with the fileseries approach on the docker container (v1.17)
Results were ok, but many stitching artefacts (blurryness, shifts) were present. 

I decided to take a deeper dive and perform some QC in python, and this leads me to think that there is some problem going on.

Stitching settings: 
max_shift=30, sigma_filter=1 

Figure 1.1
Error vs. Shift for EdgeAligner for cycles 0
You can see that many edges have very large shifts

![Screenshot 2024-04-10 at 13 39 07](https://github.com/labsyspharm/ashlar/assets/30318135/5261bfee-cbfb-4c0f-820c-dc1aa0c581ff)

Figure 1.2
Error vs. Shift for EdgeAligner for cycles 0,1
You can see that many edges have very large shifts
And the shifts are consistent between the two cycles (I was afraid that cycle 0 had poor nuclear stain)

![20240410_1316_scatter_shift_error](https://github.com/labsyspharm/ashlar/assets/30318135/bbe1e3db-b6b2-4b06-b68c-53be60e82405)

Figure 2: Edge Shift Plot
only a couple of bright edges, but most interestingly, the centers of the images (nodes) are on the edges of the plotted squares. 
You can also see that 10x10 grid is being plotted, and lastly, the images have 0.5 overlap, (crazy I know). And I dont see this overlap in the plotted images.. I feel something is off.

![Screenshot 2024-04-10 at 13 33 11](https://github.com/labsyspharm/ashlar/assets/30318135/f01de58f-7b05-402f-af3d-271a9b4c4a0b)

Figure 3: Edge Quality Plot
This gives me a clue, the diagonal edges are being much brighter than the nondiagonal edges..
And the spanning tree has mostly diagonal connections.. 

![Screenshot 2024-04-10 at 13 36 29](https://github.com/labsyspharm/ashlar/assets/30318135/b77c2dc6-8b76-4035-b664-a1424c435316)

Open Questions:
Is imaging with 50% overlap non compatible with ashlar's assumptions? 
any hints to why this dataset is not working? 
I am very confused how it got a ok stitching, but hard to get better. I can share more data if you want to see what I got.

Thanks for the feedback,
Jose

**Comment by Yu-AnChen** [comment]
Thanks for the detailed info and data. I have not tried your data but from the edge quality figure it seems that [the current method for building the neighbors graph](https://github.com/labsyspharm/ashlar/blob/387eff51b5961874e99458735efd36e0f0dc2b84/ashlar/reg.py#L459-L478) doesn't work well for the 50% overlap. I'm guessing there's barrel/pincushion distortion in each FOV, with large overlap and the current blending approach, the resulting mosaic is going to be quite blurry...

I would recommend writing up a script to center-crop each FOV and use that as input for ashlar with the new overlap fraction. Or you could also modify the source code to build the neighbors graph properly.

**Comment by josenimo** [comment]
Thank you @Yu-AnChen, 
I will freeze this for now,
