### ISSUE TITLE
Installation Instructions Discrepancy

### ISSUE THREAD

**Issue by afong3** [labsyspharm/ashlar#221]
A colleague and I both installed ASHLAR onto our respective machines. In this process I noticed that the README mentions to install python3.10 in a conda environment while the ['Installation' page on the Github.io](https://labsyspharm.github.io/ashlar/instructions/installation.html) page advises to install python3.7. Just wanted to bring this to your attention as this installs different versions from pip.

Thanks for the great tool.

**Comment by jmuhlich** [comment]
Thanks for noticing, I just fixed this.
