### ISSUE TITLE
Upgrade to newer Bio-Formats version

### ISSUE THREAD

**Issue by dsudar** [labsyspharm/ashlar#229]
Currently ashlar is deployed with Bio-Formats 6.3.1 dating back to 2019. There have been many new features, better support for a number of PFF's, and bug fixes since. I'm specifically looking to have ashlar support ZSTD compression in Zeiss .czi files which was introduced in version 6.8.0.

**Comment by dsudar** [comment]
Also, I noticed that ashlar uses the loci_tools.jar package which has the log4j vulnerability. Current versions of Bio-Formats no longer provide that package in favor of the bioformats_package.jar so there's also a security reason to upgrade.

**Comment by jmuhlich** [comment]
Sure, this is a pretty quick fix.

**Comment by dsudar** [comment]
I had missed that https://github.com/labsyspharm/ashlar/issues/138 already asked for it :-)
