### ISSUE TITLE
Dimension of the default illumination profile is not correct 

### ISSUE THREAD

**Issue by Yu-AnChen** [labsyspharm/ashlar#42]
https://github.com/labsyspharm/ashlar/blob/113d9853a7f526cf515301b00f65eccc6d9fbfc5/ashlar/reg.py#L854

From the `numpy.atleast`_3d [doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.atleast_3d.html)
> a 1-D array of shape (N,) becomes a view of shape (1, N, 1)

So here we would want to specify the shape when calling `np.zeros`. A suggested solution is 
`skimage.io.imread(dfp_path) if dfp_path else np.zeros((1, 1, c))`

**Comment by jmuhlich** [comment]
Fixed by #43
