### ISSUE TITLE
Support non-uniform-grid positions in panel files

### ISSUE THREAD

**Issue by pvarshavskaya** [labsyspharm/ashlar#50]
BioFormats now supports `.rcpnl` files with potentially non-grid positions of tiles. https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/RCPNLReader.java
Can ashlar support it too?

**Comment by pvarshavskaya** [comment]
I think simply updating the LOCI_TOOLS_* variables in setup.py will fix it

**Comment by jmuhlich** [comment]
Do you have an example of a .rcpnl with non-grid positions, and does BioFormats v5.9 actually fail to read it correctly? I haven't looked at how much work it will be to upgrade Ashlar to BioFormats 6, but it's on my short list of things to investigate. I'd like to include it in Ashlar v2.0.0 along with removal of Python 2 support (which I just completed).

**Comment by jmuhlich** [comment]
I just tested BioFormats 6 and it did not require any Ashlar code changes, so I'll merge that ASAP.

**Comment by pvarshavskaya** [comment]
Thank you!

**Comment by jmuhlich** [comment]
We did some in-house testing with an .rcpnl with multiple discontinuous ROIs and Ashlar v1.9.0 and it worked fine.
