### ISSUE TITLE
AttributeError: 'loci.formats.ome.OMEXMLMetadata' 

### ISSUE THREAD

**Issue by mariokreutzfeldt** [labsyspharm/ashlar#60]
Hi,

I am trying to register "normal" TIF images (no WSI or pyramidal TIF). 
But I get the following error:

```
.../ashlar/reg.py", line 244, in _init_metadata
    xml_content = metadata.dumpXML()
AttributeError: 'loci.formats.ome.OMEXMLMetadata' object has no attribute 'dumpXML'
```

I tried with multichannel and greyscale versions, but run into the same issue.

Best regards,
Mario

**Comment by jmuhlich** [comment]
Could you run both `java -version` (one dash) and `ashlar --version` (two dashes) and paste the output here? Thanks.

**Comment by mariokreutzfeldt** [comment]
sure:
```
java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)
```
```
ashlar --version
ashlar 1.8.
```0

**Comment by jmuhlich** [comment]
Try updating to the latest Ashlar, v1.9.0 (or master from GitHub). The issue you're seeing should be resolved in that version.

**Comment by mariokreutzfeldt** [comment]
Hi, 
this helped, indeed. Now I get 40 lines further ;)

`reg.py", line 284, in pixel_size
    v = method(0).value(UNITS.MICROMETER).doubleValue()
AttributeError: 'NoneType' object has no attribute 'value'`

Please find an example image, [here](https://www.dropbox.com/s/xpxeidft3iz9qxs/ashlar_test_image.zip?dl=0)

Best regards,
Mario

**Comment by jmuhlich** [comment]
Thanks for including an example image, that's extremely helpful! It turns out there are a lot of places where the code assumes there is more than one tile to align, but I think I've accounted for all of them in PR #61. Try `pip install git+https://github.com/labsyspharm/ashlar.git@refs/pull/61/head` and see if that works for you. I ran it with your example image duplicated as cycle 1 and 2, and it worked (albeit with a lot of expected warnings):

```
Cycle 0:
    reading /home/jmuhlich/dloads/round1_dapi.tif
/home/jmuhlich/development/ashlar/ashlar/reg.py:357: UserWarning: Stage coordinates undefined; falling back to (0, 0).
  "Stage coordinates undefined; falling back to (0, 0)."
/home/jmuhlich/development/ashlar/ashlar/reg.py:287: UserWarning: Pixel size undefined; falling back to 1.0 μm.
  "Pixel size undefined; falling back to 1.0 \u03BCm."
    assembling thumbnail 1/1
/home/jmuhlich/development/ashlar/ashlar/reg.py:478: UserWarning: No tiles overlap, attempting alignment anyway.
  warnings.warn("No tiles overlap, attempting alignment anyway.")

    Channel 0:
        merging tile 1/1
        writing to output/temp/cycle_0_channel_0.tif
Cycle 1:
    reading /home/jmuhlich/dloads/round2_dapi.tif
/home/jmuhlich/development/ashlar/ashlar/reg.py:357: UserWarning: Stage coordinates undefined; falling back to (0, 0).
  "Stage coordinates undefined; falling back to (0, 0)."
/home/jmuhlich/development/ashlar/ashlar/reg.py:287: UserWarning: Pixel size undefined; falling back to 1.0 μm.
  "Pixel size undefined; falling back to 1.0 \u03BCm."
    assembling thumbnail 1/1
    estimated cycle offset [y x] = [0. 0.]
    aligning tile 1/1
    Channel 0:
        merging tile 1/1
        writing to output/temp/cycle_1_channel_0.tif
```

**Comment by mariokreutzfeldt** [comment]
Glad the image helped!  
Another error :/ Not sure why, though. If I manually go to the URL I can download loci_tools.jar without problems.

```
  running build_py
  Ensuring latest bioformats is present:
      Downloading BioFormats from https://downloads.openmicroscopy.org/bio-formats/6.3.1/artifacts/loci_tools.jar ...
  error: <urlopen error [Errno 11] Resource temporarily unavailable>
  ----------------------------------------
  ERROR: Failed building wheel for ashlar
```

**Comment by jmuhlich** [comment]
Can you run setup.py again and see if it succeeds at fetching loci_tools.jar now? That error looks like a lower-level networking problem on your end.

**Comment by mariokreutzfeldt** [comment]
@jmuhlich 
after rerunning setup.py, ashlar is building and running. Alignment fails, though.

Trying to align 2 rounds based on dapi 8-bit greyscale images:

`ashlar round1.tif round2.tif --align-channel 0`

Throwing the following errors. Probably due to the fact that these are single images.
The final result files are modified but not aligned.

```
ashlar/reg.py:357: UserWarning: Stage coordinates undefined; falling back to (0, 0).
  "Stage coordinates undefined; falling back to (0, 0)."

ashlar/reg.py:287: UserWarning: Pixel size undefined; falling back to 1.0 μm.
  "Pixel size undefined; falling back to 1.0 \u03BCm."
    assembling thumbnail 1/1

ashlar/reg.py:478: UserWarning: No tiles overlap, attempting alignment anyway.
  warnings.warn("No tiles overlap, attempting alignment anyway.")
```

Best regards,
Mario

**Comment by jmuhlich** [comment]
Thanks for the update -- I found one more place where single-tile datasets were violating some assumptions and fixed it. Could you please try v1.11.1 to see if it finally works?

**Comment by mariokreutzfeldt** [comment]
@jmuhlich Thank you so much for your efforts! I am happy to report that it works now as expected!

Best regards,
Mario

**Comment by jmuhlich** [comment]
Glad I could help, and thanks again for your patient feedback. Feel free to reach out directly via email (see my profile) if you’d like to talk about applications — I think we might be working on similar things.
