### ISSUE TITLE
Stitching result only has one stripe

### ISSUE THREAD

**Issue by huanlity** [labsyspharm/ashlar#92]
Some of my MCMICRO processed image results are not complete. As one of the examples `hta5_1180_1403` shown below, it only has the first column and is missing the rest of the mosaic. I also include some other examples in the screenshot that has horizontal stripe. I am guessing it is the Ashlar step that is failing but I am not sure. Have you ever experienced this before? Is there a way to fix this? Thank you!

Troubleshoot information:

- I had success on very similar data before. They share the same imaging platform, configure.
- I thought it might be the insufficient overlap between columns, but 10% overlap worked well on some other dataset.

<img width="1863" alt="Screen Shot 2021-07-26 at 12 41 44 PM" src="https://user-images.githubusercontent.com/26349803/127030399-3b1de828-d2f2-4f61-9c7f-e7462b7f4948.png">

Code used:
<img width="1513" alt="Screen Shot 2021-07-26 at 1 27 20 PM" src="https://user-images.githubusercontent.com/26349803/127032484-9b5cf656-ffe2-45c4-bfea-038bc59bd56c.png">

**Comment by Yu-AnChen** [comment]
Hi @huanlity, could you plot and share the image with me using the following snippet

```python
from ashlar import fileseries, thumbnail
import matplotlib.pyplot as plt
from ashlar.scripts.ashlar import process_axis_flip

reader_1 = fileseries.FileSeriesReader(
    'raw/cycle0'
    pattern='Cycle_0_F{series:3}.tif',
    overlap=0.10,
    width=6,
    height=19,
    layout='snake',
    direction='vertical',
    pixel_sizes=0.325,
)
process_axis_flip(reader_1, flip_x=False, flip_y=True)
thumbnail_1 = thumbnail.make_thumbnail(reader_1)

reader_2 = fileseries.FileSeriesReader(
    'raw/cycle0'
    pattern='Cycle_0_F{series:3}.tif',
    overlap=0.10,
    width=6,
    height=19,
    layout='snake',
    direction='horizontal',
    pixel_sizes=0.325,
)
process_axis_flip(reader_2, flip_x=False, flip_y=True)
thumbnail_2 = thumbnail.make_thumbnail(reader_2)

fig, axs = plt.subplots(1, 2)
for a, i in zip(axs, [thumbnail_1, thumbnail_2]):
    a.imshow(i)
```

**Comment by huanlity** [comment]
@Yu-AnChen Thank you for your quick response and please see the screenshot below:

<img width="802" alt="Screen Shot 2021-07-26 at 4 06 00 PM" src="https://user-images.githubusercontent.com/26349803/127051972-a8b97837-ca55-4927-a2ab-dcefc9e9b34b.png">

**Comment by Yu-AnChen** [comment]
Thanks @huanlity, so that confirms the `layout` and `direction` were correct. And next is to check whether our algorithm is failing due to how the tissue is distributed in the scanning area. The following code should generate 4 figures -

```python
from ashlar import fileseries, reg
import matplotlib.pyplot as plt
from ashlar.scripts.ashlar import process_axis_flip

c1r = fileseries.FileSeriesReader(
    'raw/cycle0'
    pattern='Cycle_0_F{series:3}.tif',
    overlap=0.10,
    width=6,
    height=19,
    layout='snake',
    direction='vertical',
    pixel_sizes=0.325,
)
process_axis_flip(c1r, flip_x=False, flip_y=True)

c1e = reg.EdgeAligner(c1r, filter_sigma=1, verbose=True)
c1e.run()
reg.plot_edge_quality(c1e, img=c1e.reader.thumbnail)
plt.gca().suptitle('c1e')


c1e_m = reg.EdgeAligner(c1r, filter_sigma=1. max_shift=30, verbose=True)
c1e_m.run()
reg.plot_edge_quality(c1e_m, img=c1e_m.reader.thumbnail)
plt.gca().suptitle('c1e_m')

# plot_edge_scatter function requires seaborn
reg.plot_edge_scatter(c1e)
plt.gca().suptitle('c1e')

reg.plot_edge_scatter(c1e_m)
plt.gca().suptitle('c1e_m')
```

**Comment by huanlity** [comment]
<img width="669" alt="Screen Shot 2021-07-26 at 7 53 44 PM" src="https://user-images.githubusercontent.com/26349803/127073760-2764b1da-0433-43cd-b219-a93f22bb2e89.png">
<img width="669" alt="Screen Shot 2021-07-26 at 7 53 50 PM" src="https://user-images.githubusercontent.com/26349803/127073778-818c6f2e-8ffd-46f1-aa27-114ddfd3b401.png">
![Screen Shot 2021-07-26 at 7 54 24 PM](https://user-images.githubusercontent.com/26349803/127073793-13e75afc-9a74-4b9a-a142-9e3b149753f4.png)
![Screen Shot 2021-07-26 at 7 54 32 PM](https://user-images.githubusercontent.com/26349803/127073808-aff68914-9d5f-4e98-bba2-580227fa2d17.png)

**Comment by Yu-AnChen** [comment]
Those plots suggest that the shifts between neighboring tiles are between 40-50 pixels, currently the default constrain (the horizontal dotted line in the second pair) is 15 µm (15/0.325=46.15 pixels), by increasing it to 30 µm (92.3 pixels, the dotted horizontal line in the plot on the right) should give you reasonable stitching results. 

Adding `-m 30` (`-m 20` would work fine too) to your call should work ok. For example - 
```python
cmd_stitch_register = f"ashlar {full_f_series} --flip-y --filter-sigma 1 -m 30 --ffp {full_ffp_series} --dfp {full_dfp_series}"
```

The most ideal situation is to move the vertical dotted line a bit to the right (~3 in the above plot), where it separates the two distribution mode (the blue stacked histogram on the top), it may be achieved by setting a bigger `filter_sigma` in the aligner constructor, but could also introduce other issues. You could play with that parameters too. Like so - 
```python
c1e = reg.EdgeAligner(c1r, filter_sigma=2, verbose=True)
```

**Comment by huanlity** [comment]
@Yu-AnChen I did get a reasonable stitching. Thank you so much! This is really helpful!
