### ISSUE TITLE
Apply Image Correction before generating stitched images

### ISSUE THREAD

**Issue by sophiamaedler** [labsyspharm/ashlar#97]
I am imaging large areas with a spinning disk confocal microscope and want to stitch the images with ashlar. Before stitching I would like to normalize the ranges in each image to a range between 0 and 1 representing the 1-99% quantile of the signal in that image. Since I am working with several TB of data which I need to process its quite important for me that my code runs efficiently and quickly. 

The images I obtain from the microscope are exported as individual .TIF files. I have gotten a stitching pipeline working as follows where the individual images are read from file. 
```
#read data 
slide = filepattern.FilePatternReader(path = outdir_corrected, pattern = pattern, overlap = overlap)

#flip y-axis to comply with labeling generated by opera phenix
process_axis_flip(slide, flip_x=False, flip_y=True)

#perform actual alignment
aligner = reg.EdgeAligner(slide, channel='Alexa488', filter_sigma=1, verbose=True, do_make_thumbnail=False)
aligner.run()

#generate some QC plots
#reg.plot_edge_quality(aligner, img=aligner.reader.thumbnail)
reg.plot_edge_scatter(aligner)

#generate stitched file
mosaic_args = {}
mosaic_args['channels'] = lookup.label.tolist()
mosaic_args['verbose'] = True

mosaic = reg.Mosaic(aligner, 
                    aligner.mosaic_shape, 
                    SlideName + '_{channel}.tif',
                    **mosaic_args
                    )

#output result to array in python -> need to perform cropping
merged = mosaic.run(mode='return')
merged_array = np.array(merged)
```
Now I would like to somehow implement that before stitching my tiles I can apply the correction I described above to each of my tiles. I have a function which I implemented in numba which can apply this correction very quickly to stack of image tifs saved as an array in the form (N,C,W,H). Is there someway that I can apply this correction within ashlar after loading the images and before performing the stitching? 
Alternatively is there a possibility for me to pass an array containing the images that should be stitched to ashlar instead of having ashlar read from a file?
In both situations I would end up having to only read and write my data to file once which would save me a lot of time as this is currently the most time-consuming bottle neck.
Many thanks!

**Comment by Yu-AnChen** [comment]
Hi @sophiamaedler, thanks for trying out ASHLAR! Sorry for the lack of documentation, looks like you've already looked into other issues here and worked your way through it 👍  

Here's my naive attempt to solve your use case

```python
from ashlar import filepattern
import numpy as np
import skimage.exposure
import skimage.util

class FilePatternReaderRescale(filepattern.FilePatternReader):

    def __init__(self, path, pattern, overlap, pixel_size=1, do_rescale=False):
        super().__init__(path, pattern, overlap, pixel_size=pixel_size)
        self.do_rescale = do_rescale

    @staticmethod
    def rescale_p1_p99(img):
        img = skimage.util.img_as_float32(img)
        p1 = np.percentile(img, 1)
        p99 = np.percentile(img, 99)
        return skimage.exposure.rescale_intensity(
            img, in_range=(p1, p99), out_range=(0, 1)
        )
    
    def read(self, series, c):
        img = super().read(series, c)
        if not self.do_rescale:
            return img
        else:
            return self.rescale_p1_p99(img)
```

I imagine that you would replace my `rescale_p1_p99` function with your numba function. If I were to use my `rescale_p1_p99` function, I'll find the 1st and 99th percentile intensity values first, and use that value pair for ALL my image tiles instead of finding and applying the percentiles within each tile.

I'm choosing to only turn on the rescaling only when assembling the mosaic, with the consideration that the rescale may remove some useful signals during phase correlation, plus it will run a bit faster in that step. (And it will need more codes to workaround this.)

So I'd change the snippet you provided above to the following

```python
#read data 
slide = FilePatternReaderRescale(path = outdir_corrected, pattern = pattern, overlap = overlap)

#flip y-axis to comply with labeling generated by opera phenix
process_axis_flip(slide, flip_x=False, flip_y=True)

#perform actual alignment
aligner = reg.EdgeAligner(slide, channel='Alexa488', filter_sigma=1, verbose=True, do_make_thumbnail=False)
aligner.run()

#generate some QC plots
#reg.plot_edge_quality(aligner, img=aligner.reader.thumbnail)
reg.plot_edge_scatter(aligner)


# Turn on the rescaling
slide.do_rescale = True
aligner.reader = slide


#generate stitched file
mosaic_args = {}
mosaic_args['channels'] = lookup.label.tolist()
mosaic_args['verbose'] = True

mosaic = reg.Mosaic(aligner, 
                    aligner.mosaic_shape, 
                    SlideName + '_{channel}.tif',
                    **mosaic_args
                    )


# Change mosaic output dtype
mosaic.dtype = np.float32


#output result to array in python -> need to perform cropping
merged = mosaic.run(mode='return')
merged_array = np.array(merged)
```

Hope this helps!

**Comment by jmuhlich** [comment]
Thanks Yu-An! I think the line `aligner.reader = slide` is not needed though as `aligner.reader` is still referencing the same object. :)

**Comment by Yu-AnChen** [comment]
Thanks @jmuhlich you are right, but we do need to clear the cache for the channel used for alignment, so maybe instead of doing 
```python
aligner.reader = slide
```
one can do 
``` python
aligner.reader._cache = {}
```

**Comment by sophiamaedler** [comment]
Thank you so much this works perfectly for me! My pipeline is now well over 2X faster.
